# Generated by Django 5.2.8 on 2025-11-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('proveedor', 'nombre'), name='unique_producto_por_proveedor'),
        ),
    ]
