# Generated by Django 4.2 on 2025-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_unique_producto_por_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=999, null=True),
        ),
    ]
