# Generated by Django 5.2.8 on 2025-11-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda')),
            ],
            options={
                'db_table': 'proveedor',
                'constraints': [models.UniqueConstraint(fields=('tienda', 'nombre'), name='unique_proveedor_por_tienda')],
            },
        ),
    ]
