# Generated by Django 4.2 on 2025-11-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('es_superusuario', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PermisosUsuarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_gestionar_proveedores', models.BooleanField(default=True)),
                ('puede_gestionar_productos', models.BooleanField(default=True)),
                ('puede_gestionar_compras', models.BooleanField(default=True)),
                ('puede_ver_inventario_compras', models.BooleanField(default=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'db_table': 'permisos_usuario_tienda',
            },
        ),
        migrations.AddConstraint(
            model_name='permisosusuariotienda',
            constraint=models.UniqueConstraint(fields=('usuario', 'tienda'), name='unique_usuario_por_tienda'),
        ),
    ]
