# Generated by Django 4.2 on 2025-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosusuariotienda',
            name='puede_editar_compras',
            field=models.BooleanField(default=True),
        ),
    ]
