# Generated by Django 5.2.8 on 2025-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('producto', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('proveedor', 'fecha_compra'), name='unique_compra_proveedor_fecha'),
        ),
        migrations.AddConstraint(
            model_name='detallecompra',
            constraint=models.UniqueConstraint(fields=('compra', 'producto'), name='unique_producto_por_compra'),
        ),
    ]
